spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbmultimedia?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:/templates/
  mail:
    host: smtp.qq.com
    username: 1781587589@qq.com
    password: xjtbjrgxwvhieced
    default-encoding: UTF-8
  server:
    port: 8080
  com:
    ccr: ${server.port}
  minMoney: 1